apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-github-auth-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: grafana-github-oauth-app
        property: client_id
      secretKey: client_id
    - remoteRef:
        key: grafana-github-oauth-app
        property: client_secret
      secretKey: client_secret
  target:
    name: grafana-github-auth-secret
