[env]
OP_ACCOUNT="HROTQCZ2CJBCRGUOJ6EJKIT7XU"
AWS_PROFILE = "home"
AWS_REGION = "eu-central-1"

[tools]
python = "3.14.0"
pipx = "latest"

ansible = "11.2.0"
"aqua:bitnami-labs/sealed-secrets" = "0.33.1"
"aqua:fluxcd/flux2" = "2.7.3"
"aqua:go-task/task" = "3.45.4"
"aqua:hashicorp/terraform" = "1.13.5"
"aqua:helm/helm" = "3.19.1"
"aqua:helmfile/helmfile" = "1.1.9"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.32.1"
"aqua:mikefarah/yq" = "4.48.1"
