apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - helmrepository.yaml
  - httproute-external.yaml
  - httproute-internal.yaml
  - pvc.yaml
  - securitypolicy.yaml
