apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envoy-internal-github-oauth-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: envoy-internal-github-oauth-app
        property: client_id
      secretKey: client-id
    - remoteRef:
        key: envoy-internal-github-oauth-app
        property: client_secret
      secretKey: client-secret
  target:
    name: envoy-internal-github-oauth-app
