apiVersion: v1
kind: Service
metadata:
  name: home-assistant-openthread-br
  labels:
    app.kubernetes.io/name: home-assistant-openthread-br
spec:
  type: ClusterIP
  ports:
    - name: http-web
      port: 8080
      targetPort: http-web
    - name: http-rest
      port: 8081
      targetPort: http-rest
  selector:
    app.kubernetes.io/name: home-assistant-openthread-br
