apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws
  - cert-manager
  - external-dns
  - external-secrets
  - flux-system
  - github-actions-runner
  - kube-system
  - longhorn
  - network
  - monitoring
  - sealed-secrets
