apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: seerr
        property: api-key
      secretKey: API_KEY
  target:
    name: seerr
