apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-commit-status
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: github-commit-status-token
        property: token
      secretKey: token
  target:
    name: github-commit-status
