apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: ovh-credentials
        property: OVH_APPLICATION_KEY
      secretKey: OVH_APPLICATION_KEY
    - remoteRef:
        key: ovh-credentials
        property: OVH_APPLICATION_SECRET
      secretKey: OVH_APPLICATION_SECRET
    - remoteRef:
        key: ovh-credentials
        property: OVH_CONSUMER_KEY
      secretKey: OVH_CONSUMER_KEY
  target:
    name: ovh-credentials
